-- ==========================================
-- Fix RLS Policies for Admin Order Processing
-- ==========================================

-- 1. Storage Bucket Policies: 'Plagreports'
-- ==========================================
-- Ensure the bucket exists (in case it wasn't created via dashboard)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('Plagreports', 'Plagreports', true)
ON CONFLICT (id) DO NOTHING;

-- Policy to allow authenticated users (Admins) to upload files to 'Plagreports' bucket
CREATE POLICY "Allow Authenticated Uploads to Plagreports"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'Plagreports' );

-- Policy to allow authenticated users to read files from 'Plagreports' bucket
CREATE POLICY "Allow Authenticated Select from Plagreports"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'Plagreports' );


-- 2. Table Policies: 'Plagdocs'
-- ==========================================
-- Ensure the table exists (Schema inferred from ProcessOrder.jsx)
CREATE TABLE IF NOT EXISTS public.Plagdocs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "Name" text,
    "UserID" text,
    "AIvalue" text,
    "AIDoc" text,
    "Plagvalue" text,
    "PlagDoc" text
);

-- Enable RLS
ALTER TABLE public.Plagdocs ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to INSERT records into 'Plagdocs'
CREATE POLICY "Allow Authenticated INSERT on Plagdocs"
ON public.Plagdocs FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy to allow authenticated users to SELECT (view) records
CREATE POLICY "Allow Authenticated SELECT on Plagdocs"
ON public.Plagdocs FOR SELECT
TO authenticated
USING (true);


-- 3. Table Policies: 'Tasks'
-- ==========================================
-- Admin needs to update the 'progress' field in 'Tasks'
ALTER TABLE public.Tasks ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to UPDATE tasks
-- Note: In a production app with roles, you should restrict this to Admins only.
CREATE POLICY "Allow Authenticated UPDATE on Tasks"
ON public.Tasks FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);
