-- Drop existing table if needed (WARNING: Data loss)
DROP TABLE IF EXISTS "public"."Notifications";

-- Create Notifications Table with specified schema
CREATE TABLE "public"."Notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" character varying NOT NULL, -- Matched to user request string type? Or FK? User said "character varying string". Supabase auth.users id is usually uuid. If User table uses string/varchar IDs, this is correct. If FK to auth.users, it should be uuid. I will stick to user request "character varying".
    "message" character varying NOT NULL,
    "is_read" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Enable RLS
ALTER TABLE "public"."Notifications" ENABLE ROW LEVEL SECURITY;

-- Note: The foreign key constraint was removed in this version based on the user's table description 
-- which didn't explicitly ask for an FK constraint, just the column types. 
-- If user_id corresponds to Users.User_id (which might be uuid or varchar depending on setup), logic holds.

-- Policy: Users can see their own notifications
-- We need to cast auth.uid() to text if user_id is varchar
CREATE POLICY "Users can view their own notifications" 
ON "public"."Notifications"
FOR SELECT 
USING (auth.uid()::text = user_id);

-- Policy: Authenticated users can insert
CREATE POLICY "Authenticated users can insert notifications" 
ON "public"."Notifications"
FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');
