-- ==========================================
-- Fix Missing 'Tasks' Table and RLS
-- ==========================================

-- 1. Create 'Tasks' Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.Tasks (
    "Task_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "Name" text,
    "Item" text,
    "Service" text,
    "UserID" bigint, -- Assumes UserID maps to Users.User_id (bigint)
    "progress" boolean DEFAULT false
);

-- 2. Enable RLS on 'Tasks'
-- ==========================================
ALTER TABLE public.Tasks ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies for 'Tasks'
-- ==========================================

-- Allow Authenticated Users to Insert (e.g. creating a new order)
CREATE POLICY "Allow Authenticated INSERT on Tasks"
ON public.Tasks FOR INSERT
TO authenticated
WITH CHECK (true);

-- Allow Authenticated Users to Select (e.g. viewing their own orders)
CREATE POLICY "Allow Authenticated SELECT on Tasks"
ON public.Tasks FOR SELECT
TO authenticated
USING (true);

-- Allow Authenticated Users (Admins) to Update (e.g. marking as complete)
CREATE POLICY "Allow Authenticated UPDATE on Tasks"
ON public.Tasks FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);
