-- Run this SQL in your Supabase SQL Editor to create the 'Users' table
-- as per your requirements.

CREATE TABLE public.Users (
    User_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    FullNmae character varying, -- Using the exact spelling provided
    Email character varying,
    PhoneNo character varying
    -- Note: Passwords are handled securely by Supabase Auth (auth.users).
    -- We do not store them here to avoid security risks.
);

-- Enable Row Level Security (RLS) is recommended
ALTER TABLE public.Users ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to insert (for signup) 
-- or you can restrict it to authenticated users only if you trigger it differently.
-- For simple signup flow where client inserts directly:
CREATE POLICY "Enable insert for everyone" ON public.Users FOR INSERT WITH CHECK (true);

-- Policy to allow users to read/update their own data is recommended later.
